apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-plugin
config:
  origins: "*"
  methods: "GET,PUT,PATCH,POST,DELETE"
---

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth-plugin
---

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: anonymous-consumer
username: anonymous
---

apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: anonymous-credential
consumerRef: anonymous-consumer
type: key-auth
config:
  key: anonymous
